name = "oauth-staging"
type = "javascript"

account_id = '35641a6e50a31e745078ec7a010c2a6f'
# route = ''
# zone_id = ''

compatibility_flags = []
workers_dev = true
compatibility_date = "2022-02-04"

[build]
command = "yarn build"

[build.upload]
format = "modules"
main = "./index.mjs"

[[migrations]]
tag = "v1"

[miniflare]

[vars]
TWITTER_CLIENT_ID = "VUFqaVZVc1RLUzFtMTdIWGJWMG46MTpjaQ"
TWITTER_API_KEY = "WI7NcqAuiGLdX8d4SY4tUCvvu"
TWITTER_ACCESS_TOKEN = "333748468-QGFhPpAxxhekphkuCfc6gn58PfjBJf8aIlgPONYP"


route = "stag.depub.space/oauth/*"

# Override values for `--env production` usage
[env.prod]
name = "oauth"
route = "depub.space/oauth/*"

# [secrets]
# TWITTER_CLIENT_SECRET
# TWITTER_API_SECRET_KEY
# TWITTER_ACCESS_TOKEN_SECRET