name = "depub-space-graphql-staging"
type = "javascript"

account_id = '35641a6e50a31e745078ec7a010c2a6f'
# route = ''
# zone_id = ''

compatibility_flags = []
workers_dev = true
compatibility_date = "2022-02-04"
webpack_config = "webpack.config.js"
kv_namespaces = [
  { binding = "WORKERS_GRAPHQL_CACHE", id = "9cf0a6d5091e448c9411e8ee8c65acb6" }
]

[build]
command = "yarn build"

[build.upload]
format = "service-worker"

[vars]
LIKECOIN_RPC_ENDPOINT = "https://node.testnet.like.co/rpc/"
ISCN_FINGERPRINT = "https://depub.blog"
DESMOS_GRAPHQL_ENDPOINT = "https://gql.mainnet.desmos.network/v1/graphql"
CACHE_TTL = 60 # 1min
ENVIRONMENT = "staging"

# Override values for `--env production` usage
[env.prod]
name = "depub-space-graphql"
kv_namespaces = [
  { binding = "WORKERS_GRAPHQL_CACHE", id = "5acfb215b0d34d8fa20d921d1e40c699" }
]

[env.prod.vars]
LIKECOIN_RPC_ENDPOINT = "https://mainnet-node.like.co/rpc/"
ISCN_FINGERPRINT = "https://depub.blog"
DESMOS_GRAPHQL_ENDPOINT = "https://gql.mainnet.desmos.network/v1/graphql"
CACHE_TTL = 600 # 10min
ENVIRONMENT = "production"